import type { TMonstersData } from "@pages/monsters/monster.model";

export const staticMonstersData: TMonstersData = {
  'weretiger-tiger': {
    damage: 25,
    experience: 100,
    health: 300,
    name: 'Weretiger',
    src: 'monsters/weretiger.jpg',
  },
  'werewolf-human': {
    damage: 50,
    experience: 150,
    health: 350,
    name: 'Werewolf, Human Form',
    src: 'monsters/werewolf1.jpg',
  },
  'werewolf-hybrid': {
    damage: 45,
    experience: 120,
    health: 280,
    name: 'Werewolf, Hybrid Form',
    src: 'monsters/werewolf2.jpg',
  },
  'werewolf-wolf': {
    damage: 80,
    experience: 90,
    health: 180,
    name: 'Werewolf, Wolf Form',
    src: 'monsters/werewolf3.jpg',
  },
  'wight': {
    damage: 70,
    experience: 130,
    health: 250,
    name: 'Wight',
    src: 'monsters/whisp.png',
  },
  'will-o-wisp': {
    damage: 50,
    experience: 110,
    health: 200,
    name: 'Will-O-Wisp',
    src: 'monsters/wight.png',
  },
  'winter-wolf': {
    damage: 70,
    experience: 100,
    health: 150,
    name: 'Winter Wolf',
    src: 'monsters/winter-wolf.png',
  },
  'wolf': {
    damage: 25,
    experience: 80,
    health: 250,
    name: 'Wolf',
    src: 'monsters/wolf.jpg',
  },
  'worg': {
    damage: 25,
    experience: 90,
    health: 300,
    name: 'Worg',
    src: 'monsters/worg.jpg',
  },
  'wraith': {
    damage: 25,
    experience: 70,
    health: 130,
    name: 'Wraith',
    src: 'monsters/wraith.jpg',
  },
  'wyvern': {
    damage: 25,
    experience: 200,
    health: 500,
    name: 'Wyvern',
    src: 'monsters/will-o-wisp.png',
  },
  'xorn': {
    damage: 40,
    experience: 300,
    health: 700,
    name: 'Xorn',
    src: 'monsters/xorn.jpg',
  },
  'zombie': {
    damage: 25,
    experience: 180,
    health: 500,
    name: 'Zombie',
    src: 'monsters/zombie.jpg',
  },
}
